# Generated by Django 4.2.24 on 2025-09-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
